name: Maruf

on:
  workflow_dispatch:
    inputs:
      THE_NAME:
        description: prayer_times_app
        type: string
        required: true

      MAIN_PY:
        description: Python main filename
        type: string
        required: true
        default: maruf.py

      #NO_WINDOWS:
      #  description: Do not build for Windows, just Linux
      #  type: boolean
      #  required: true
      #  default: false
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Get site-packages path
        id: site
        shell: bash
        run: |
          echo "SITE=$(python -c 'import site; print(site.getsitepackages()[0].replace("\\\\", "/"))')
          echo "SITE_PACKAGES=$SITE" >> $GITHUB_ENV" >> $GITHUB_ENV

      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: maruf.py
          mode: onefile
          enable-plugins: pyside6
          include-data-dir: |
            ${{ env.SITE_PACKAGES }}/numpy=numpy
            resources=resources
          include-raw-dir: |
            ${{ env.SITE_PACKAGES }}/timezonefinder=timezonefinder

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
            build/*.dist/**/*
          include-hidden-files: true
      - name: Create Git Tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag v${{ github.run_number }}
      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Maruf Release v1.0.${{ github.run_number }}"
          tag_name: "v1.0.${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/*.exe
            build/*.bin
          tag_name: "v${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
