name: Maruf

on:
  workflow_dispatch:
    inputs:
      THE_NAME:
        description: prayer_times_app
        type: string
        required: true

      MAIN_PY:
        description: Python main filename
        type: string
        required: true
        default: maruf.py

      #NO_WINDOWS:
      #  description: Do not build for Windows, just Linux
      #  type: boolean
      #  required: true
      #  default: false
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
          cache: 'pip'
          cache-dependency-path: |
            **/requirements*.txt

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Get site-packages path
        id: site
        shell: python
        run: |
          import os
          import numpy, timezonefinder
          with open(os.environ["GITHUB_ENV"], "a", encoding="utf-8") as f:
            f.write(f"NUMPY_DIR={os.path.dirname(numpy.__file__).replace('\\\\', '/')}\n")
            f.write(f"TIMEZONEFINDER_DIR={os.path.dirname(timezonefinder.__file__).replace('\\\\', '/')}\n")
      - name: Debug paths
        run: |
          echo "NUMPY_DIR: ${{ env.NUMPY_DIR }}"
          echo "TIMEZONEFINDER_DIR: ${{ env.TIMEZONEFINDER_DIR }}"



      - name: Build Executable
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: maruf.py
          mode: onefile
          enable-plugins: pyside6
          include-data-dir: |
            ${{ env.NUMPY_DIR }}/_core=numpy/_core
            resources/maruf_assets=maruf_assets/resources
            ${{ env.TIMEZONEFINDER_DIR }}=timezonefinder
          include-data-files: |
            ${{ env.TIMEZONEFINDER_DIR }}/hole_adr2data.bin=timezonefinder/hole_adr2data.bin
            ${{ env.TIMEZONEFINDER_DIR }}/hole_coord_amount.bin=timezonefinder/hole_coord_amount.bin
            ${{ env.TIMEZONEFINDER_DIR }}/hole_data.bin=timezonefinder/hole_data.bin
            ${{ env.TIMEZONEFINDER_DIR }}/poly_adr2data.bin=timezonefinder/poly_adr2data.bin
            ${{ env.TIMEZONEFINDER_DIR }}/poly_bounds.bin=timezonefinder/poly_bounds.bin
            ${{ env.TIMEZONEFINDER_DIR }}/poly_coord_amount.bin=timezonefinder/poly_coord_amount.bin
            ${{ env.TIMEZONEFINDER_DIR }}/poly_data.bin=timezonefinder/poly_data.bin
            ${{ env.TIMEZONEFINDER_DIR }}/poly_nr2zone_id.bin=timezonefinder/poly_nr2zone_id.bin
            ${{ env.TIMEZONEFINDER_DIR }}/poly_zone_ids.bin=timezonefinder/poly_zone_ids.bin
            ${{ env.TIMEZONEFINDER_DIR }}/shortcuts.bin=timezonefinder/shortcuts.bin
          output-file: |
            maruf_${{ runner.os,, }}_${{ runner.arch,, }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Build
          path: |
            build/*.exe
            build/*.bin
            build/*.app/**/*
            build/*.dist/**/*
          include-hidden-files: true
      - name: Create Git Tag
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git tag v1.1.${{ github.run_number }}
      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Maruf Release v1.1.${{ github.run_number }}"
          files: |
            build/*.exe
            build/*.bin
            LICENSE.md
          tag_name: "v1.1.${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
